language: go

go:
  - 1.5.2
  - tip

before_install:
  - mv ${TRAVIS_BUILD_DIR}/server/Godeps ${TRAVIS_BUILD_DIR}
  - npm install -g bower

before_script:
  - make setup

script:
  - make test

notifications:
  email: false

matrix:
  allow_failures:
    - go: tip
